# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WarpDiagChecker < Formula
  desc "Simple tool to check for known warp issues"
  homepage "https://github.com/peakefficiency/warp-diag-checker"
  version "0.6.0"

  on_macos do
    url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.6.0/warp-diag-checker_Darwin_all.tar.gz"
    sha256 "5e924dfe5caf6278d743bb06eed584f7409e8b8c291330f59dd34fe162d74291"

    def install
      bin.install "warp-diag-checker"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.6.0/warp-diag-checker_Linux_armv6.tar.gz"
      sha256 "807193ce3281c122f8e9dce137c7e3e61cc53521719fcf9577452dcc2a94c470"

      def install
        bin.install "warp-diag-checker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.6.0/warp-diag-checker_Linux_x86_64.tar.gz"
      sha256 "3a0d0a1916f5395536053d65de8b08df7f39463462282d01110f54ccee36852f"

      def install
        bin.install "warp-diag-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.6.0/warp-diag-checker_Linux_arm64.tar.gz"
      sha256 "fada2836413d41b1c5176631f94e072bda6b29adc48efda9a56b8460b8a1af7d"

      def install
        bin.install "warp-diag-checker"
      end
    end
  end

  def caveats
    <<~EOS
      More information here: https://github.com/peakefficiency/warp-diag-checker
    EOS
  end
end
