# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WarpDiagChecker < Formula
  desc "Simple tool to check for known warp issues"
  homepage "https://github.com/peakefficiency/warp-diag-checker"
  version "0.7.1"

  on_macos do
    url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.7.1/warp-diag-checker_Darwin_all.tar.gz"
    sha256 "5c1e4290398f9227080656fb9c3e74e050f04c3a4657f15d06b5e49e174ca392"

    def install
      bin.install "warp-diag-checker"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.7.1/warp-diag-checker_Linux_armv6.tar.gz"
      sha256 "61130f8f617d06299f75046f7ece84f9bbe1d60bc41faedcda37b581ccc1d508"

      def install
        bin.install "warp-diag-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.7.1/warp-diag-checker_Linux_arm64.tar.gz"
      sha256 "2e4995a79c62d18c233124bd85b6b3066f2a80a64a1d87a45d6e1b6fce5e7659"

      def install
        bin.install "warp-diag-checker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/peakefficiency/warp-diag-checker/releases/download/0.7.1/warp-diag-checker_Linux_x86_64.tar.gz"
      sha256 "ef6ad9168291e8f2b71a3d70b3e027f047ab3d7e707f96759c700316a5f5848f"

      def install
        bin.install "warp-diag-checker"
      end
    end
  end

  def caveats
    <<~EOS
      More information here: https://github.com/peakefficiency/warp-diag-checker
    EOS
  end
end
